/* Generated by AN DISI Unibo */ 
package it.unibo.orchestrator

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Orchestrator ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
			   	val DMIN = 50 
			   	var Synced = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 clearlog("./logs/app_firefly.log")  
						createActorDynamically("firefly", "_1", false)
						createActorDynamically("firefly", "_2", false)
						createActorDynamically("firefly", "_3", false)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | in attesa di dati dal sonar...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleSonar",cond=whenEvent("sonardata"))
				}	 
				state("handleSonar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("distance(D)"), Term.createTerm("distance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val D = payloadArg(0).toInt()  
								if(  D < DMIN && !Synced  
								 ){CommUtils.outred("$name | Distanza $D < $DMIN. Invio SYNC!")
								 Synced = true  
								emit("sync", "sync(1000)" ) 
								}
								if(  D >= DMIN && Synced  
								 ){CommUtils.outgreen("$name | Distanza $D >= $DMIN. Invio UNSYNC!")
								 Synced = false  
								emit("unsync", "unsync(ok)" ) 
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
} 
