/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
			   var X = 0 
			   var Y = 0 
			   var Timer = 500L
			   var state = false
			   
			   fun setCellCoords( ) { 
			   	   val coordY = name.replace("firefly_","") 
			   	   Y = coordY.toInt() 
			   }
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 setCellCoords( )  
						 Timer = java.util.Random().nextLong(1000L, 2000L )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="turnOn", cond=doswitch() )
				}	 
				state("turnOn") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_turnOn", 
				 	 					  scope, context!!, "local_tout_"+name+"_turnOn", 500.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t10",targetState="turnOff",cond=whenTimeout("local_tout_"+name+"_turnOn"))   
					transition(edgeName="t11",targetState="handlesync",cond=whenEvent("switch_state"))
				}	 
				state("turnOff") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_turnOff", 
				 	 					  scope, context!!, "local_tout_"+name+"_turnOff", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t22",targetState="turnOn",cond=whenTimeout("local_tout_"+name+"_turnOff"))   
					transition(edgeName="t23",targetState="handlesync",cond=whenEvent("switch_state"))
				}	 
				state("handlesync") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("switch_state(TIMER)"), Term.createTerm("switch_state(A)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
											   state = !state
											   if(state){
											   	val t = payloadArg(0) 
											   	val T = t.toLong() 
											   	Timer = T 
											   } else {
											   	Timer = java.util.Random().nextLong(1000L, 2000L )
											   }
								CommUtils.outgreen("$name | Ricevuta frequenza $T")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="turnOn", cond=doswitch() )
				}	 
			}
		}
} 
