/* Generated by AN DISI Unibo */ 
package it.unibo.sender

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sender ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var emitEvents = true   
			   var DT         = 1000L; 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName} handling $currentMsg"  )  
						CommUtils.outgreen("$name sends msg1: msg1(1)... ")
						 logger.info(  "${currentState.stateName} sending msg1:msge1(1)"  )  
						forward("msg1", "msg1(1)" ,"receiver" ) 
						delay(300) 
						CommUtils.outgreen("$name sends msg1: msg1(2)... ")
						 logger.info(  "${currentState.stateName} sending msg1:msge1(2)"  )  
						forward("msg1", "msg1(2)" ,"receiver" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_s0", 
				 	 					  scope, context!!, "local_tout_"+name+"_s0", DT )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="sendothermsgs",cond=whenTimeout("local_tout_"+name+"_s0"))   
				}	 
				state("sendothermsgs") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName} handling $currentMsg"  )  
						CommUtils.outgreen("$name sends msg2 after $DT ... ")
						 logger.info(  "${currentState.stateName} sending msg2:msg2(1)"  )  
						forward("msg2", "msg2(1)" ,"receiver" ) 
						if(  emitEvents  
						 ){ logger.info(  "${currentState.stateName} emits alarm"  )  
						emit("alarm", "alarm(fire)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
