/* Generated by AN DISI Unibo */ 
package it.unibo.radar_req_rep

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Radar_req_rep ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 
				var D = 0
				var Timer = 1000L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | starting")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="rileva_distanza", cond=doswitch() )
				}	 
				state("rileva_distanza") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_rileva_distanza", 
				 	 					  scope, context!!, "local_tout_"+name+"_rileva_distanza", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t01",targetState="rileva_distanza",cond=whenTimeout("local_tout_"+name+"_rileva_distanza"))   
					transition(edgeName="t02",targetState="handleRequest",cond=whenRequest("getDistance"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("getDistance(D)"), Term.createTerm("getDistance(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								answer("getDistance", "radar_repl", "distance($D)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleRequest", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleRequest", Timer )  //OCT2023
					}	 	 
					 transition(edgeName="t03",targetState="rileva_distanza",cond=whenTimeout("local_tout_"+name+"_handleRequest"))   
				}	 
			}
		}
} 
